name: Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: Setup lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: Setup luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup test environment
        shell: bash
        run: luarocks install vusted

      - name: Run tests
        shell: bash
        run: make run_tests
